---
name: ðŸ“¦ Publish to Ansible Galaxy

on:
  release:
    types:
      - created

jobs:
  publish:
    name: ðŸš€ Publish role to Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Check out the codebase
        uses: actions/checkout@v4

      - name: ðŸ Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ðŸ“¦ Install Ansible dependencies
        run: |
          pip3 install ansible-core

      - name: ðŸš€ Upload role to Ansible Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
